# Generated by Django 5.2.7 on 2025-10-29 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocionproducto',
            name='cantidad_gratis',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promocionproducto',
            name='cantidad_requerida',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promocionproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddField(
            model_name='promocionproducto',
            name='producto_gratis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_gratis', to='core.producto'),
        ),
        migrations.AddField(
            model_name='promocionproducto',
            name='variante_gratis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_gratis_variante', to='core.productovariante'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tipo_descuento',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto Fijo'), ('x_por_y', '(2x1, 3x2, etc.)')], max_length=20),
        ),
    ]
