# Generated by Django 5.2.7 on 2025-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_direccion_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_url_base',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
