# Generated by Django 5.2.7 on 2025-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoria_imagen_url_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='imagen_logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
