# Generated by Django 5.2.7 on 2025-11-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_marca_imagen_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cupon_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='descuento_global_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
