"""
Django settings for JhomilWebApp project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url # MÓDULO AÑADIDO: Para manejar la URL de la base de datos de Render


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# MODIFICADO: Ahora lee la clave secreta desde la variable de entorno SECRET_KEY
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-*6hcq#a(lgoe)k=a01(x-4wj#p0nzy%xx-(+4+z^(n4a_5#p*r')

# SECURITY WARNING: don't run with debug turned on in production!
# MODIFICADO: Lee el estado de DEBUG desde la variable de entorno
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# MODIFICADO: Lee los hosts permitidos desde la variable de entorno
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
# Si está en modo DEBUG (local), permite todos los hosts para desarrollo
if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Si quisieras servir archivos estáticos (como el Admin), necesitarías añadir 'whitenoise.middleware.WhiteNoiseMiddleware' aquí
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'JhomilWebApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'JhomilWebApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# MODIFICADO: Configuración para PostgreSQL usando DATABASE_URL de Render

DATABASES = {
    'default': dj_database_url.config(
        # Lee la variable de entorno DATABASE_URL
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600, # Tiempo de vida máximo de la conexión
    )
}

# Configuración obligatoria para conexiones SSL a PostgreSQL de Render
if os.environ.get('DATABASE_URL'):
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# CONFIGURACIÓN ADICIONAL PARA ESTÁTICOS EN PRODUCCIÓN (Render)
if not DEBUG:
    # Ruta donde Django recolectará todos los archivos estáticos
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'